### ISSUE TITLE
Cannot create new classifier #5

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-contraxsuite#10]
![image](https://user-images.githubusercontent.com/3324817/30857837-9c1f4ce8-a300-11e7-8f63-71ef6ed2ead1.png)

Class Name is required, it's a select, but it has no values.

(From https://github.com/LexPredict/lexpredict-legal-dictionary/issues/5)

**Comment by mjbommar** [comment]
Please see note from issue #11.

Also, no pre-trained text unit classifiers are shipped in 1.0.1.  Users can build their own classifiers through at least two options:
1. Training via the UI (see images below)
2. Training via data science notebooks (Jupyter; see example notebooks in repo)

A.
![image](https://user-images.githubusercontent.com/85053/30858653-8e86bbba-a28e-11e7-9a62-da952bf5086d.png)

B.
![image](https://user-images.githubusercontent.com/85053/30858697-ba803660-a28e-11e7-977a-eac9a1dfd76e.png)

OR
C.
![image](https://user-images.githubusercontent.com/85053/30858811-3da497ac-a28f-11e7-9626-6d15d1ab7322.png)


1.0.2 and 1.0.3 will ship with open source pre-trained classifiers from public domain data, so you will see this interface change soon as well.
