### ISSUE TITLE
No documents found after uploading PDF documents

### ISSUE THREAD

**Issue by dwmcqueen** [LexPredict/lexpredict-contraxsuite#22]
I was successfully able to use the txt based samples to upload and run the locate task.  I cleared them out and uploaded two PDFs.  When running the admin "Locate command" after uploading and running Elasticsearch, nothing was identified.  This was the task details:

NFO 2018-01-18 15:18:19,662 | Run location of [amount; trademark; court; currency; regulation; date; ratio; citation; duration; url; definition; distance; geoentity; party; term; copyright; percent].
INFO 2018-01-18 15:18:19,665 | Locate in [paragraphs].
INFO 2018-01-18 15:18:19,670 | Found 0 Text Units. Added 0 subtasks.
INFO 2018-01-18 15:18:19,777 | End of main task "Locate", id=20

Amy I missing a step that needs to be taken with PDF documents or do they manually need to be converted to text prior to uploading?

**Comment by mviktorov** [comment]
Hi.

You uploaded them via file browser and than run "Load Documents", right?

"Load Documents" is for loading documents from files to DB, parsing PDFs into plain text e.t.c.
"Locate..." is to locate entities in the documents' texts.

**Comment by dwmcqueen** [comment]
Nope - I didn't run Load Documents.  All is well now!
