### ISSUE TITLE
NameError: name 'Document' is not defined'

### ISSUE THREAD

**Issue by zahid1123** [LexPredict/lexpredict-contraxsuite#27]
I have recently installed Contraxsuite with manual installation. I want to use notebook example codes for sample documents. I put some sample documents in following directory,
"anaconda3/lib/python3.6/site-packages/django/apps/lexpredict-contraxsuite/contraxsuite_services/media/data/documents"

My code is following,

```
> import os
> import sys
> import pandas
> import matplotlib.pyplot as plt

> sys.path.append("/home/takken/anaconda3/lib/python3.6/site-packages/django/apps/lexpredict-contraxsuite/")

> import django
> from django.db import IntegrityError
> os.environ['DJANGO_SETTINGS_MODULE'] = 'django.apps.lexpredict-contraxsuite.contraxsuite_services.settings'
> django.setup()

> import nltk
> from apps.document import *
> from apps.task.utils.nlp import *
> from apps.task.utils.text import *
> from apps.task.tasks import normalize, stem_tokens, stemmer
> 
> for d in Document.objects.all()[0:10]:
>     print(d)
```

when i run the code, following error happens,

> NameError                                 Traceback (most recent call last)
> <ipython-input-1-6370d0f5c88e> in <module>()
>      18 from apps.task.tasks import normalize, stem_tokens, stemmer
>      19 
> ---> 20 for d in Document.objects.all()[0:10]:
>      21     print(d)
> 
> NameError: name 'Document' is not defined'

Is there any mistake in importing documents? or the procedure is not correct?

**Comment by reddalexx** [comment]
You didn't import Document - this model is in apps.document.models,
so you should import it like this:
from apps.document.models import Document

**Comment by reddalexx** [comment]
It means that you didn't run "Load Documents" admin task
1. you should upload documents in a system - see Tasks > Browse/Upload Documents
2. then Tasks > Admin Tasks > Run Task > Load Documents: point to a folder or to a document
if you ran application properly and celery works it will produce Document objects for you

**Comment by zahid1123** [comment]
@reddalexx 
can you help me to find "Load Documents" admin task? Where can I run this?

**Comment by reddalexx** [comment]
Main Menu > Tasks > Admin Tasks > Button "Run Task" > Load Data > Load Documents

**Comment by zahid1123** [comment]
Sir @reddalexx ! I am not using UI. as I didn't have licensed version of it. 
is there a way to use UI? It will solve all my problems I think.

**Comment by reddalexx** [comment]
this should work:
from apps.users.models import User
from apps.task.tasks import call_task

                call_task(
                    task_name='LoadDocuments',
                    source_path=<your_relative_path_here>,
                    user_id=User.object.get(pk=<your_pk>)

but you should ensure that celery works before running tasks
activate virtual environment
in project directory run
celery status -A apps

and run celery it it's down
celery multi start 2 -A apps -f log.txt

**Comment by zahid1123** [comment]
- celery status returned "OK" 2 times in activated environment.
- celery muilti start also returned "OK"

My code is as follow now;
```
%matplotlib inline

# Standard imports
import os
import sys

# Data science imports
import pandas
import matplotlib.pyplot as plt

# Setup path
sys.path.append("../")
sys.path.append("../contraxsuite_services/")
sys.path.append("/opt/ve/lib/python3.5/site-packages/")
sys.path.append("/opt/lexpredict-contraxsuite/contraxsuite_services/")
sys.path.append("/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services")


# Django imports
import django
from django.db import IntegrityError

# Setup django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "django.apps.contraxsuite_services.settings")
django.setup()

from apps.users.models import User
from apps.task.tasks import call_task
#     print(User)

call_task(task_name='LoadDocuments', 
          source_path='/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
          user_id=User.object.get(pk = User.pk))

```
but it is returning;

```
AttributeError  Traceback (most recent call last)
<ipython-input-17-acf239ba7b3b> in <module>()
     31 call_task(task_name='LoadDocuments', 
     32           source_path='/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
---> 33           user_id=User.object.get(pk = User.pk))

AttributeError: type object 'User' has no attribute 'object
```

**Comment by reddalexx** [comment]
sorry
User.objects...
i.e. objects instead of object

**Comment by ericlex** [comment]
@zahid1123 You should use the GUI as thats been built out and tested. I would recommend you purchase a license to the HTML theme and begin from the GUI. Please set up the GUI and let us know if you run into any issues.

**Comment by zahid1123** [comment]
@reddalexx 
```
from apps.users.models import User
from apps.task.tasks import call_task
# print(User.objects.all())
for _user in User.objects.all():
    print("User:", _user)
    print ("PrimaryKey of User:", (PK.pk))
    print("Call_task returned:", 
          call_task(task_name='LoadDocuments', 
          source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
         user_id=User.objects.get(pk = _user.pk)))

from apps.document.models import Document
print("Documents: ")
# print(Document)
for d in Document.objects.all()[0:10]:
    print(d)
```
and the Output was,
`TypeError                             Traceback (most recent call last)
<ipython-input-25-fe09c78b8495> in <module>()
     33           source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
     34 
---> 35           user_id=User.objects.get(pk = _user.pk)))
     36 
     37 from apps.document.models import Document

/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/apps/task/tasks.py in call_task(task_name, **options)
    156         celery_task_id=task_id,
    157         user_id=options.get('user_id'),
--> 158         metadata=options.get('metadata')
    159     )
    160     options['task_id'] = task.id

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in create(self, **kwargs)
    392         obj = self.model(**kwargs)
    393         self._for_write = True
--> 394         obj.save(force_insert=True, using=self.db)
    395         return obj
    396 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)
    805 
    806         self.save_base(using=using, force_insert=force_insert,
--> 807                        force_update=force_update, update_fields=update_fields)
    808     save.alters_data = True
    809 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    835             if not raw:
    836                 self._save_parents(cls, using, update_fields)
--> 837             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    838         # Store the database on which the object was saved
    839         self._state.db = using

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    921 
    922             update_pk = meta.auto_field and not pk_set
--> 923             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    924             if update_pk:
    925                 setattr(self, meta.pk.attname, result)

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _do_insert(self, manager, using, fields, update_pk, raw)
    960         """
    961         return manager._insert([self], fields=fields, return_id=update_pk,
--> 962                                using=using, raw=raw)
    963 
    964     def delete(self, using=None, keep_parents=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in _insert(self, objs, fields, return_id, raw, using)
   1074         query = sql.InsertQuery(self.model)
   1075         query.insert_values(fields, objs, raw=raw)
-> 1076         return query.get_compiler(using=using).execute_sql(return_id)
   1077     _insert.alters_data = True
   1078     _insert.queryset_only = False

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in execute_sql(self, return_id)
   1096         self.return_id = return_id
   1097         with self.connection.cursor() as cursor:
-> 1098             for sql, params in self.as_sql():
   1099                 cursor.execute(sql, params)
   1100             if not (return_id and cursor):

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in as_sql(self)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1048         if has_fields:
   1049             value_rows = [
-> 1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
   1051                 for obj in self.query.objs
   1052             ]

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in prepare_value(self, field, value)
    988                 raise FieldError("Aggregate functions are not allowed in this query")
    989         else:
--> 990             value = field.get_db_prep_save(value, connection=self.connection)
    991         return value
    992 

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/related.py in get_db_prep_save(self, value, connection)
    961             return None
    962         else:
--> 963             return self.target_field.get_db_prep_save(value, connection=connection)
    964 
    965     def get_db_prep_value(self, value, connection, prepared=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_save(self, value, connection)
    768         """
    769         return self.get_db_prep_value(value, connection=connection,
--> 770                                       prepared=False)
    771 
    772     def has_default(self):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_value(self, value, connection, prepared)
    956     def get_db_prep_value(self, value, connection, prepared=False):
    957         if not prepared:
--> 958             value = self.get_prep_value(value)
    959             value = connection.ops.validate_autopk_value(value)
    960         return value

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_prep_value(self, value)
    964         if value is None:
    965             return None
--> 966         return int(value)
    967 
    968     def contribute_to_class(self, cls, name, **kwargs):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'User'`
 
and then I change the line, 
`user_id=_user.pk`
and Then Output shown as, 
```
User: demo
PrimaryKey of User: 1
Call_task returned: 33
Documents: 
```@reddalexx 
```
from apps.users.models import User
from apps.task.tasks import call_task
# print(User.objects.all())
for _user in User.objects.all():
    print("User:", _user)
    print ("PrimaryKey of User:", (PK.pk))
    print("Call_task returned:", 
          call_task(task_name='LoadDocuments', 
          source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
         user_id=User.objects.get(pk = _user.pk)))

from apps.document.models import Document
print("Documents: ")
# print(Document)
for d in Document.objects.all()[0:10]:
    print(d)
```
and the Output was,
`TypeError                             Traceback (most recent call last)
<ipython-input-25-fe09c78b8495> in <module>()
     33           source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
     34 
---> 35           user_id=User.objects.get(pk = _user.pk)))
     36 
     37 from apps.document.models import Document

/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/apps/task/tasks.py in call_task(task_name, **options)
    156         celery_task_id=task_id,
    157         user_id=options.get('user_id'),
--> 158         metadata=options.get('metadata')
    159     )
    160     options['task_id'] = task.id

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in create(self, **kwargs)
    392         obj = self.model(**kwargs)
    393         self._for_write = True
--> 394         obj.save(force_insert=True, using=self.db)
    395         return obj
    396 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)
    805 
    806         self.save_base(using=using, force_insert=force_insert,
--> 807                        force_update=force_update, update_fields=update_fields)
    808     save.alters_data = True
    809 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    835             if not raw:
    836                 self._save_parents(cls, using, update_fields)
--> 837             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    838         # Store the database on which the object was saved
    839         self._state.db = using

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    921 
    922             update_pk = meta.auto_field and not pk_set
--> 923             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    924             if update_pk:
    925                 setattr(self, meta.pk.attname, result)

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _do_insert(self, manager, using, fields, update_pk, raw)
    960         """
    961         return manager._insert([self], fields=fields, return_id=update_pk,
--> 962                                using=using, raw=raw)
    963 
    964     def delete(self, using=None, keep_parents=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in _insert(self, objs, fields, return_id, raw, using)
   1074         query = sql.InsertQuery(self.model)
   1075         query.insert_values(fields, objs, raw=raw)
-> 1076         return query.get_compiler(using=using).execute_sql(return_id)
   1077     _insert.alters_data = True
   1078     _insert.queryset_only = False

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in execute_sql(self, return_id)
   1096         self.return_id = return_id
   1097         with self.connection.cursor() as cursor:
-> 1098             for sql, params in self.as_sql():
   1099                 cursor.execute(sql, params)
   1100             if not (return_id and cursor):

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in as_sql(self)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1048         if has_fields:
   1049             value_rows = [
-> 1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
   1051                 for obj in self.query.objs
   1052             ]

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in prepare_value(self, field, value)
    988                 raise FieldError("Aggregate functions are not allowed in this query")
    989         else:
--> 990             value = field.get_db_prep_save(value, connection=self.connection)
    991         return value
    992 

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/related.py in get_db_prep_save(self, value, connection)
    961             return None
    962         else:
--> 963             return self.target_field.get_db_prep_save(value, connection=connection)
    964 
    965     def get_db_prep_value(self, value, connection, prepared=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_save(self, value, connection)
    768         """
    769         return self.get_db_prep_value(value, connection=connection,
--> 770                                       prepared=False)
    771 
    772     def has_default(self):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_value(self, value, connection, prepared)
    956     def get_db_prep_value(self, value, connection, prepared=False):
    957         if not prepared:
--> 958             value = self.get_prep_value(value)
    959             value = connection.ops.validate_autopk_value(value)
    960         return value

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_prep_value(self, value)
    964         if value is None:
    965             return None
--> 966         return int(value)
    967 
    968     def contribute_to_class(self, cls, name, **kwargs):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'User'`
 
and then I change the line, 
`user_id=_user.pk`
and Then Output shown as, 
```
User: demo
PrimaryKey of User: 1
Call_task returned: 33
Documents: 
```

**Comment by zahid1123** [comment]
```
from apps.users.models import User
from apps.task.tasks import call_task
# print(User.objects.all())
for _user in User.objects.all():
    print("User:", _user)
    print ("PrimaryKey of User:", (PK.pk))
    print("Call_task returned:", 
          call_task(task_name='LoadDocuments', 
          source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
          
          user_id=User.objects.get(pk = _user.pk))))

from apps.document.models import Document
print("Documents: ")
# print(Document)
for d in Document.objects.all()[0:10]:
    print(d)
```
was return error log as 

```
TypeError                             Traceback (most recent call last)
<ipython-input-27-fe09c78b8495> in <module>()
     33           source_path='/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/media/data/documents',
     34 
---> 35           user_id=User.objects.get(pk = _user.pk)))
     36 
     37 from apps.document.models import Document

/opt/ve/lib/python3.5/site-packages/django/apps/contraxsuite_services/apps/task/tasks.py in call_task(task_name, **options)
    156         celery_task_id=task_id,
    157         user_id=options.get('user_id'),
--> 158         metadata=options.get('metadata')
    159     )
    160     options['task_id'] = task.id

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in create(self, **kwargs)
    392         obj = self.model(**kwargs)
    393         self._for_write = True
--> 394         obj.save(force_insert=True, using=self.db)
    395         return obj
    396 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save(self, force_insert, force_update, using, update_fields)
    805 
    806         self.save_base(using=using, force_insert=force_insert,
--> 807                        force_update=force_update, update_fields=update_fields)
    808     save.alters_data = True
    809 

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in save_base(self, raw, force_insert, force_update, using, update_fields)
    835             if not raw:
    836                 self._save_parents(cls, using, update_fields)
--> 837             updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    838         # Store the database on which the object was saved
    839         self._state.db = using

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _save_table(self, raw, cls, force_insert, force_update, using, update_fields)
    921 
    922             update_pk = meta.auto_field and not pk_set
--> 923             result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    924             if update_pk:
    925                 setattr(self, meta.pk.attname, result)

/opt/ve/lib/python3.5/site-packages/django/db/models/base.py in _do_insert(self, manager, using, fields, update_pk, raw)
    960         """
    961         return manager._insert([self], fields=fields, return_id=update_pk,
--> 962                                using=using, raw=raw)
    963 
    964     def delete(self, using=None, keep_parents=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/manager.py in manager_method(self, *args, **kwargs)
     83         def create_method(name, method):
     84             def manager_method(self, *args, **kwargs):
---> 85                 return getattr(self.get_queryset(), name)(*args, **kwargs)
     86             manager_method.__name__ = method.__name__
     87             manager_method.__doc__ = method.__doc__

/opt/ve/lib/python3.5/site-packages/django/db/models/query.py in _insert(self, objs, fields, return_id, raw, using)
   1074         query = sql.InsertQuery(self.model)
   1075         query.insert_values(fields, objs, raw=raw)
-> 1076         return query.get_compiler(using=using).execute_sql(return_id)
   1077     _insert.alters_data = True
   1078     _insert.queryset_only = False

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in execute_sql(self, return_id)
   1096         self.return_id = return_id
   1097         with self.connection.cursor() as cursor:
-> 1098             for sql, params in self.as_sql():
   1099                 cursor.execute(sql, params)
   1100             if not (return_id and cursor):

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in as_sql(self)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1049             value_rows = [
   1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
-> 1051                 for obj in self.query.objs
   1052             ]
   1053         else:

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in <listcomp>(.0)
   1048         if has_fields:
   1049             value_rows = [
-> 1050                 [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
   1051                 for obj in self.query.objs
   1052             ]

/opt/ve/lib/python3.5/site-packages/django/db/models/sql/compiler.py in prepare_value(self, field, value)
    988                 raise FieldError("Aggregate functions are not allowed in this query")
    989         else:
--> 990             value = field.get_db_prep_save(value, connection=self.connection)
    991         return value
    992 

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/related.py in get_db_prep_save(self, value, connection)
    961             return None
    962         else:
--> 963             return self.target_field.get_db_prep_save(value, connection=connection)
    964 
    965     def get_db_prep_value(self, value, connection, prepared=False):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_save(self, value, connection)
    768         """
    769         return self.get_db_prep_value(value, connection=connection,
--> 770                                       prepared=False)
    771 
    772     def has_default(self):

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_db_prep_value(self, value, connection, prepared)
    956     def get_db_prep_value(self, value, connection, prepared=False):
    957         if not prepared:
--> 958             value = self.get_prep_value(value)
    959             value = connection.ops.validate_autopk_value(value)
    960         return value

/opt/ve/lib/python3.5/site-packages/django/db/models/fields/__init__.py in get_prep_value(self, value)
    964         if value is None:
    965             return None
--> 966         return int(value)
    967 
    968     def contribute_to_class(self, cls, name, **kwargs):

TypeError: int() argument must be a string, a bytes-like object or a number, not 'User'
```
then I changed the line,
`user_id= _user.pk
`
and it showed only, 

```
User: demo
PrimaryKey of User: 1
Call_task returned: 34
Documents: 
```

**Comment by zahid1123** [comment]
@ericlex ! Welcome. 
Sure I ought to get license of UI. But seems that I have just 1 or 2 steps far to output. So I dont think so I will get need of it.

**Comment by SatinderpalSingh** [comment]
from frappe.website.website_generator import Document

That solves my error.

**Comment by ashaseeb** [comment]
In my case, this error "**Document' is not defined**" started appearing right after I enabled "**Has Web View**" during the document customization and when I was trying to uncheck this option was not allowed and the document was not defined error was appearing along with different route etc messages when I was trying to revert however, let's discuss how I resolved this issue?  

The reason of this error was, that the Document reference got changed when you enabled "Has Web View" option so you need to write document reference in .py file manually. Let's suppose, your customised form name is MyCustomDoc

1- Locate your MyCustomDoc.py file which should be in apps/{myApp}/{myModule}/doctype/MyCustomDoc/MyCustomDoc.py
2- Copy and paste this import => import frappe from frappe.model.document import Document
3- Save and restart the bench
4- Go back to DocType List=>MyCustomDoc and Unmark "Has Web View" and remove "route" field if you added any.
5- The issue will be fixed!

<img width="988" alt="capture" src="https://github.com/user-attachments/assets/c5a58a93-7335-4474-bf02-ceac754f039b">


<img width="537" alt="Capture2" src="https://github.com/user-attachments/assets/783c726b-5089-4964-aa3b-5ad4c32cbad4">
