### ISSUE TITLE
LexPredict ContraxSuite - Deploy Scripts not functioning properly

### ISSUE THREAD

**Issue by bhaveshp3** [LexPredict/lexpredict-contraxsuite#3]
https://github.com/LexPredict/lexpredict-contraxsuite-deploy script is not working as mentioned in the guide
I am installing on same machine so I have modified required files **setup_local.sh** and other files  but it stopped moving ahead at the **"Login Password for 'ubuntu'"** even after entering Correct password

My Linux OS : **Ubuntu 16.04** 

Please refer the attached file.

![ice_screenshot_20170817-200606](https://user-images.githubusercontent.com/16354213/29418996-9178b80e-838b-11e7-8e2e-fcc5d1e525b5.png)

**Comment by mjbommar** [comment]
Hello @bhaveshp3 , can you please email support@contraxsuite.com with your fabricrc?  We can help you more easily from this mailing list, especially if you need to share private details.

As a quick note, I think you are executing the script as `root` but have left the default `user=ubuntu`  line in `local/fabricrc`.  Our instructions assume you are running as non-root user with `sudo` privileges.  Assuming this is a stock AWS machine based on your hostname and command prompt, can you try again as just `ubuntu`?

**Comment by bhaveshp3** [comment]
Hello Mjbommar
Thank you for quick reply.
I have tried executing with Linux User 'ubuntu' with default user=ubuntu line mentioned in local/fabric but still same error.
At the same time, I will email to support@contraxsuite.com
Thank you.

**Comment by mjbommar** [comment]
Thanks, @bhaveshp3.  We received your email.  Someone from the team will report back tomorrow to you.

**Comment by mjbommar** [comment]
Hello @bhaveshp3,
  We are closing this duplicate issue so that we can track it here:
https://github.com/LexPredict/lexpredict-contraxsuite-deploy/issues/1

  Please subscribe to the issue there for more notifications.
