### ISSUE TITLE
Provide a docker container definition

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-contraxsuite#4]
It would be great if there was a docker container that I could just fire up so that I could have a play around. I'm going through the installation steps now and there's quite a bit to do before I can get my hands dirty. Would be great if all that was abstracted away.

**Comment by gemmell** [comment]
Didn't realise just how much the lexpredict-contraxsuite-deploy does for you! Trivial to build a docker container.

**Comment by mjbommar** [comment]
@gemmell , thanks, this is a great suggestion!

We have a list of deployment approaches that we're targeting internally, but would be curious if you had other platforms/approaches you'd like to see covered.  For example, would you also be interested in an AWS Marketplace image or a VMware image?

**Comment by gemmell** [comment]
So for now, I'm looking at this just to get a feel for it and see what it's capabilities are, and it would be best if that was extremely easy to do. I think in terms of making it deployable anywhere you could set up a series of docker containers each with it's own service with some docker orchestration for a single machine deployment and a docker orchestration for multi-machine. Something like that would mean it's deployable in house or in the cloud. Perhaps using kubernetes or something like that. 

I feel like any deployment is going to need some serious consulting with the customer to work out loads etc, so I don't know that you should put a huge amount of effort into it at the moment. Make it really accessible so that I can try it (perhaps host it somewhere so I can log in and upload a document and see what it does to it?) and when people start to try to deploy it someone will build the systems to solve the deployment problems.
