### ISSUE TITLE
Add Canvas theme instructions to Installation and Configuration Guide

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-contraxsuite#5]
After running lexpredict-contraxsuite-deploy and logging in, I'm note that it can't find a large portion of CSS & JS. In the place where it's looking for them is a single REAME.md with:
`Please see the Installation and Configuration Guide for more details on obtaining the Canvas theme.`

Unfortunately there is no mention of Canvas in the Installation and Configuration Guide.

**Comment by gemmell** [comment]
Ah, instructions are in the "Software and Data Dependencies" doc.

**Comment by mjbommar** [comment]
Thanks, @gemmell.  Better instructions on this step are coming tomorrow with our 1.0.1 release documentation.

**Comment by mjbommar** [comment]
@gemmell, as of 1.0.2 release, Canvas will be automatically installed through deployment automation as long as you provide the path to the distribution ZIP.  This should help simplify the documentation as well.
