### ISSUE TITLE
Improving the installation guide

### ISSUE THREAD

**Issue by alexanderjulmer** [LexPredict/lexpredict-contraxsuite#8]
These notes are based on my experience of installing ContraxSuite locally on an Ubuntu 16.04 LTS Virtual Machine. I have little experience in server administration and even less in administrating enterprise Software.

I used `setup_local.sh` to install the software and referred to the `Installation and Configuration Guide` which I rather scanned than read thoroughly. That's probably why I missed the Quick Start Guide. The section on pre-installation is a bit confusing as I haven't noticed that the installation script is actually capable of installing the necessary software. The same is true for the `Quick Start Installation Guide for Linux`.

Just as in [this issue](https://github.com/LexPredict/lexpredict-contraxsuite/issues/5) I have also overlooked the dependencies for Canvas5 and jQWidgets.

During the automatic installation process I had to install `openssh_server` before being able to use to the script. 

After installation, adding the dependencies was a bit troublesome as I had to figure out that django needs to be told to reload dependencies from the `static` folder and this reloading is not included in the start routine as described in the `Administration Guide for Linux`. I used `python manage.py collectstatic` to reload the static files which worked fine. I also had to move `style.css` from `staticfiles/theme` to `staticfiles/theme/css`. When downloaded from Themeforest, Canvas5 has `style.css` not in the `css` folder.

I would suggest to add a paragraph to the installation guide explaining how the dependencies can be added, maybe also provide a script which can pick them up and copy them in place.

**Comment by gemmell** [comment]
@alexanderjulmer where are you running collectstatic from? I'm getting `AttributeError: 'module' object has no attribute 'Path'` . A also had to install a bunch of dependencies so I assume that it's supposed to be using a python virtualenv before it's starting the server? I haven't dug into the setup scripts to work out what yet.

**Comment by gemmell** [comment]
So I found `/opt/ve` which I think might be the virtualenv, but I get the same issue

**Comment by gemmell** [comment]
The remote installation instructions don't explain what "hosts" is for in remote/fabricrc the rest is pretty self-evident, but hosts is not.

**Comment by gemmell** [comment]
OK what am I doing wrong? If I go `source /opt/ve/bin/activate` and then try to run `python manage.py collectstatic` I get 
``` File "manage.py", line 18, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
What am I missing here?

**Comment by gemmell** [comment]
Well, I never worked out what virtualenv I was supposed to use, but I did end up getting it to work by continually running `python manage.py collectstatic` and then installing the missing python modules that it complained about.

**Comment by gemmell** [comment]
It's running but after creating a project I get an error in the console `$.jqx is undefined`

**Comment by gemmell** [comment]
I am not sure what step I got wrong, but ` cp ../static/vendor/jqwidgets/jqx-all.js staticfiles/js/jqwidgets.js` gets it loading. I have spent like 3 hours on these little problems. Needs a script!

**Comment by gemmell** [comment]
Are there some demonstrative instructions as to what we need to do to set things up once inside the application? I've uploaded a bunch of documents and it's not identified a single defined term, party, or even date from the documents I've uploaded. It feels to me like I've missed some important step - oh. I found it. Tasks->Admin Tasks->Run Task->Locate and check the boxes.

**Comment by mjbommar** [comment]
Hi @gemmell , sorry to hear you had issues with jq.  1.0.2 includes automation that installs both jq and the default Canvas theme; users simply provide the path to both the theme ZIP file and jqwidgets distribution ZIP file.

Also, based on the fact that you seem to have missing python modules, we would recommend doing a clean install and carefully following the instructions again.  Did you run the installer as root or as a non-root user?

**Comment by mjbommar** [comment]
1. @gemmell, as with Canvas, 1.0.2 will support the automatic configuration of jq so long as you provide the correct path to the jqwidgets distribution ZIP.

2. @alexanderjulmer, we are adding an SSH server as a listed dependency for both local  and remote installations.

3. The post-theme/jq steps with `collectstatic` should also be unnecessary going forward, as long as the user provides the Canvas and jq distribution files in fabric.

4. We are also adding additional protections against running the install scripts as `root`.  Users will be warned and prompted if root execution is detected.
