### ISSUE TITLE
Does not like parties with an ampersand

### ISSUE THREAD

**Issue by gemmell** [LexPredict/lexpredict-contraxsuite#9]
It identifies Ted LLC as the party when actually it's Bill & Tedd LLC

**Comment by mjbommar** [comment]
Hi @gemmell, thanks for reporting this.

We have options coming in 1.0.2 that will allow you more flexibility to capture these by default:
* Option 1: NLTK entity extractor (default), which is based on part-of-speech tagging.  Currently, certain characters like punctuation make break up "chunks" of contiguous POS elements, but we will support changing these in the app.  For example, in 1.0.1:
`if chunk[1] in ["NNP", "NNPS", ".", ","]:`

* Option 2: Regular expression matcher, which is based on common entity types (see snippet below).  Again, configurable non-alphabetical characters.

* Option 3: Stanford NER, if enabled, which may capture merge based on context.  

As a warning, however, you may find that some drafters use & in very unfortunate circumstances, such as "by and between X & Y", where X and Y really should not be merged into one party (hence our default conservative behavior thus far).

From `constants.en`:
```
COMPANY_TYPES = ['Inc.', 'L.L.C.', 'Ltd.', 'L.P.', 'S.A.', 'Corp.', 'Corporation', 'Incorporated',
                 'S.A. de C.V.', 'S. de R.L. de C.V.', 'S.L.', 'AG', 'A.G.',
                 'Ltd.', 'B.V.', 'LLC.', 'Lda.', 'Ltda.', 'S.R.L.', 's.r.o.',
                 'S.A.S.', 'S.A. DE C.V.', 'C.A.', 'Corp.', 'S.L.U.', 'S.A. De C.V.',
                 'S. DE R.L. DE C.V.', 'L.L.P.', 'K.K.', 'C.V.', 'N.A.', 'Ltd.', 'S.r.l.',
                 'S.A.R.L.', 'S. de R. L. de C.V.', 'S. De R.L. De C.V.', 'S.R.L. de C.V.', 'G.P.',
                 'S.A.de C.V.', 'L.P.', 'N.V.', 'S de R.L. de C.V.', 'S.C.A.',
                 'Sdn. Bhd.', 'S.R.O.', 'L.L.L.P.', 'S.de R.L. de C.V.', 'Pte. Ltd.',
                 'S.A.U.', 'S.C.', 'S.a.r.l.', 'S. De R.L. de C.V.']
COMPANY_DESCRIPTIONS = ['Bank', 'Trust', 'Company', "Partnership"]```

**Comment by mjbommar** [comment]
@gemmell , default behavior in the upcoming release will handle this case.  For example, see results below:

```
In [1]: from lexnlp.extract.en.entities.nltk_maxent import get_companies
In [2]: list(get_companies("We are doing business with a most excellent group by the name of Bill & Tedd LLC."))
Out[2]: [('Bill & Tedd', 'LLC')]
```
